@startuml
class OrderForm <<partial>> {
    - components : System.ComponentModel.IContainer = null
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
    - lblTableNr : Label
    - btnRemoveCom : Button
    - btnAddCom : Button
    - textBoxComment : TextBox
    - label8 : Label
    - label6 : Label
    - listVOrder : ListView
    - btnLunchM : Button
    - btnDinnerM : Button
    - btnDrinksM : Button
    - btnPrevious : Button
    - btnPlus : Button
    - btnMinus : Button
    - btnClearAll : Button
    - btnSendOrder : Button
    - pnlDinner : Panel
    - pnlDrinks : Panel
    - listVCoffee : ListView
    - label19 : Label
    - label14 : Label
    - listVSpirit : ListView
    - label15 : Label
    - label16 : Label
    - label17 : Label
    - listVWines : ListView
    - listVBeers : ListView
    - listVSoftDrinks : ListView
    - label18 : Label
    - pnlLunch : Panel
    - label4 : Label
    - label3 : Label
    - label2 : Label
    - listVDessertsLunch : ListView
    - listVMainsLunch : ListView
    - listVStartersLunch : ListView
    - label1 : Label
    - label13 : Label
    - listVEntremetsDinner : ListView
    - label9 : Label
    - label10 : Label
    - label11 : Label
    - listVDessertsDinner : ListView
    - listVMainsDinner : ListView
    - listVStartersDinner : ListView
    - label12 : Label
    - columnHeader54 : ColumnHeader
    - columnHeader55 : ColumnHeader
    - columnHeader56 : ColumnHeader
    - columnHeader1 : ColumnHeader
    - columnHeader2 : ColumnHeader
    - columnHeader3 : ColumnHeader
    - columnHeader4 : ColumnHeader
    - columnHeader5 : ColumnHeader
    - columnHeader6 : ColumnHeader
    - columnHeader29 : ColumnHeader
    - columnHeader30 : ColumnHeader
    - columnHeader31 : ColumnHeader
    - columnHeader33 : ColumnHeader
    - columnHeader34 : ColumnHeader
    - columnHeader35 : ColumnHeader
    - columnHeader37 : ColumnHeader
    - columnHeader38 : ColumnHeader
    - columnHeader39 : ColumnHeader
    - columnHeader10 : ColumnHeader
    - columnHeader11 : ColumnHeader
    - columnHeader12 : ColumnHeader
    - columnHeader7 : ColumnHeader
    - columnHeader8 : ColumnHeader
    - columnHeader9 : ColumnHeader
    - columnHeader21 : ColumnHeader
    - columnHeader22 : ColumnHeader
    - columnHeader23 : ColumnHeader
    - columnHeader32 : ColumnHeader
    - columnHeader36 : ColumnHeader
    - columnHeader40 : ColumnHeader
    - columnHeader17 : ColumnHeader
    - columnHeader18 : ColumnHeader
    - columnHeader19 : ColumnHeader
    - columnHeader24 : ColumnHeader
    - columnHeader25 : ColumnHeader
    - columnHeader26 : ColumnHeader
    - columnHeader13 : ColumnHeader
    - columnHeader14 : ColumnHeader
    - columnHeader15 : ColumnHeader
    - columnHeader16 : ColumnHeader
}
@enduml
