@startuml
!include ./test/Program.puml
!include ./ChapeauUI/FreeTableActionsForm.puml
!include ./ChapeauUI/OrderForm.Designer.puml
!include ./ChapeauUI/OccupiedTableActionsForm.puml
!include ./ChapeauUI/PaymentFormCompleteBill.puml
!include ./ChapeauUI/PaymentFormCompleteBill.Designer.puml
!include ./ChapeauUI/RestaurantOverviewForm.puml
!include ./ChapeauUI/LoginForm.Designer.puml
!include ./ChapeauUI/PaymentFormSubBill.puml
!include ./ChapeauUI/RestaurantOverviewForm.Designer.puml
!include ./ChapeauUI/FreeTableActionsForm.Designer.puml
!include ./ChapeauUI/OccupiedTableActionsForm.Designer.puml
!include ./ChapeauUI/BillForm.puml
!include ./ChapeauUI/LoginForm.puml
!include ./ChapeauUI/PaymentFormSubBill.Designer.puml
!include ./ChapeauUI/OrderForm.puml
!include ./ChapeauUI/BillForm.Designer.puml
!include ./ChapeauUI/Program.puml
!include ./Model/Order.puml
!include ./Model/SubBill.puml
!include ./Model/Bill.puml
!include ./Model/Table.puml
!include ./Model/OrderItem.puml
!include ./Model/MenuItemModel.puml
!include ./Model/BillItem.puml
!include ./Model/MenuModel.puml
!include ./Model/Employee.puml
!include ./Service/BillService.puml
!include ./Service/OrderItemService.puml
!include ./Service/OrderService.puml
!include ./Service/Menu_Service.puml
!include ./Service/TableService.puml
!include ./Service/SubBillService.puml
!include ./Service/EmployeeService.puml
!include ./DAL/BillDao.puml
!include ./DAL/MenuItemDao.puml
!include ./DAL/BaseDao.puml
!include ./DAL/EmployeeDao.puml
!include ./DAL/OrderItemDao.puml
!include ./DAL/TableDao.puml
!include ./DAL/OrderDao.puml
!include ./DAL/SubBillDao.puml
!include ./ChapeauUI/Properties/Resources.Designer.puml
!include ./ChapeauUI/obj/Debug/net6.0-windows/ChapeauUI.AssemblyInfo.puml
!include ./ChapeauUI/obj/Debug/net6.0-windows/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./ChapeauUI/obj/Debug/net6.0-windows/ChapeauUI.GlobalUsings.g.puml
!include ./Model/obj/Debug/net6.0/Model.AssemblyInfo.puml
!include ./Model/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Model/obj/Debug/net6.0/Model.GlobalUsings.g.puml
!include ./Service/obj/Debug/net6.0/Service.GlobalUsings.g.puml
!include ./Service/obj/Debug/net6.0/Service.AssemblyInfo.puml
!include ./Service/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./DAL/obj/Debug/net6.0/DAL.GlobalUsings.g.puml
!include ./DAL/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./DAL/obj/Debug/net6.0/DAL.AssemblyInfo.puml
@enduml
